name: Release workflow for tagged versions
on:
  release:
    types:
      - created

jobs:
  pgbuilder-image:
    permissions:
      packages: write
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@main

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: 'Build pgbuilder image'
        run: |
          cd pgbuilder
          docker build . --tag builder
          docker tag builder ghcr.io/oriole-rpms/pgbuilder:latest
          docker tag builder ghcr.io/oriole-rpms/pgbuilder:${{ github.ref_name }}

      - name: 'Tag latest'
        run: |
          docker tag builder ghcr.io/oriole-rpms/pgbuilder:latest
          docker tag builder ghcr.io/oriole-rpms/pgbuilder:${{ github.ref_name }}

      - name: 'Push to ghcr.io'
        run: docker push -a ghcr.io/oriole-rpms/pgbuilder

  oriolepg-image:
    needs: pgbuilder-image
    permissions:
      packages: write
    runs-on: ubuntu-latest
    strategy:
      matrix:
        pgversion: ['12', '13', '14', '15', '16']
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@main

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: 'Build rpms'
        run: |
          docker-compose run pgbuilder
        env:
          PGVERSION: ${{ matrix.pgversion }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Binary RPM
          path: oriolepg/rpms/
